name: SimpleInterest
main: net.shatteredlands.shatteredbeam.simpleinterest.SimpleInterest
version: ${project.version}
softdepend: [Vault]
author: Shatteredbeam
description: SimpleInterest is a simple way to aggregate interest in player economy accounts at a regular interval.